parameters:
#    bs_front.example.class: BS\FrontBundle\Example

services:
    bs_front.admin.blog:
        class: BS\FrontBundle\Admin\BlogAdmin
        arguments: [~, BS\FrontBundle\Entity\Blog, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Блог}
